# Generated by Django 4.0.2 on 2022-02-27 06:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=300, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField(blank=True, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('category', models.ForeignKey(default='generel', on_delete=django.db.models.deletion.CASCADE, to='todo.category')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
